name: "upload"

on:
  push:

jobs:
  codeql:
    name: CodeQL Analysis
    uses: jesus-vergara/.github/.github/workflows/codeql.yml@main

  upload:
    name: Upload
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create new file
        run:
          echo "This is a new file" > new_file.txt
    
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: file
          path: new_file.txt


  download:
    name: Download
    runs-on: ubuntu-latest
    needs: upload

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: file

      - name: Print contents
        run:
          cat /home/runner/work/actions/actions/new_file.txt
